[project]
name = "modal-function-a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "modal>=0.64.92",
]


[tool.setuptools]
py-modules = []