# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class SecretA:
        type: str
        value: str
    class TestFn:
        name: str
        type: str
        url: str

